= Micro Java

A showcase collection of simple java based projects. The projects are server-side (backend) implementation for https://github.com/tastejs/todomvc[TodoMVC example] - the Backbone implementation.

The project is a showcase code for my *JEE development without a hassle* talk, where I cover multiple lightweight alternatives to traditional fully blow application stacks. 

The project is a bit inspired by https://github.com/kouphax/todomvc-server[James Hughes project] which I participated in, though with slightly changed rules:

* Focuses purely on Java frameworks
* Each example is backed with a database (MySQL)
* Database connection is indended to be as lightweight as the web stack itself

=== API

Application API confronts following endpoints:
[options="header", cols="1,2,6"]
|===
|Method | URL | Description

|GET 
|**/todos** 
|Returns JSON of all todos

|POST
|**/todos** 
|Accepts JSON encoded body returns created Todo (e.g. with the ID field populated) or Invalid response (400 Status Code) with validation errors 

|PUT 
|**/todos/[id]** 
|Accepts a JSON encoded body of a Todo and the Todo with an [id] will be updated. If [id] does not exist a 404 is returned
|=== 
